name: CI

on:
    pull_request:
    push:
        branches:
            - master
            - feature/[a-z]+-[0-9]+/dev-*
    workflow_dispatch:

jobs:
    validation:
        name: "CS, ArchSniffer, PHPStan, Security"
        runs-on: ubuntu-20.04
        env:
            APPLICATION_ENV: testing
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                    '8.0',
                    '8.1',
                ]

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl, pdo_mysql, redis
                  tools: composer:v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer validate
              run: composer validate

            - name: Composer version
              run: composer --version

            - name: Composer install
              run: composer install

            - name: Run CodeStyle checks
              run: composer cs-check

            - name: Run PHPStan
              run: composer stan

            - name: Codecept tests
              if: ${{ matrix.php-version == '8.0' }}
              run: composer test

            - name: Codecept tests with coverage
              if: ${{ matrix.php-version == '8.1' }}
              run: composer test-cover

            - uses: codecov/codecov-action@v3
              with:
                  files: ./tests/_output/coverage.xml
                  fail_ci_if_error: true
